### ISSUE TITLE
get-graphTokenForIntune : Failed to retrieve access token from Azure

### ISSUE THREAD

**Issue by iamnumpty** [ThomasKur/IntuneDocumentation#10]
Receiving following error on global admin without MFA

get-graphTokenForIntune : Failed to retrieve access token from Azure
At line:954 char:21
+ ... l:authToken = get-graphTokenForIntune -User $user -Password $password
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,get-graphTokenForIntune
 
get-graphTokenForIntune : access token is null!
At line:954 char:21
+ ... l:authToken = get-graphTokenForIntune -User $user -Password $password
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,get-graphTokenForIntune

**Comment by ThomasKur** [comment]
Hi RaptorG, does the following work https://github.com/ThomasKur/IntuneDocumentation/issues/7 ?

**Comment by iamnumpty** [comment]
Thanks that worked but then it failed again. I figured the script also requires AzureRM  Module. I ran "Install-Module AzureRM -AllowClobber" and it worked for the most part but then failed at:

Invoke-RestMethod : {"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException",
"Message":"Graph call failed with httpCode=NotFound, errorCode=Request_ResourceNotFound,
errorMessage=Resource'232e9e8e-f508-4b3b-8cc7-bf09b70523c3' does not exist or one of its queried reference-property objects are not present., 
reason=Not Found, correlationId = 17fb2996-7b64-4924-9b68-543c45145ce9, response = {\"odata.error\":{\"code\":\"Request_ResourceNotFound\",
\"message\":{\"lang\":\"en\",\"value\":\"Resource '232e9e8e-f508-4b3b-8cc7-bf09b70523c3' does not exist or one of its queried reference-property objects are not present.\"},
\"requestId\":\"bbac0b0c-25e9-4f98-9e59-5f637cb28be4\",\"date\":\"2018-11-06T10:08:14\"}}","Data":{},
"HResult":-2146233088,"XMsServerRequestId":null,"Source":null,"HttpStatusCode":404,"ClientData":{"errorCode":"Request_ResourceNotFound",
"localizedErrorDetails":{"errorDetail":"Resource '232e9e8e-f508-4b3b-8cc7-bf09b70523c3' does not exist or one ofits queried reference-property objects are not present."},
"operationResults":null,"timeStampUtc":"2018-11-06T10:08:14.890125Z",
"clientRequestId":"17fb2996-7b64-4924-9b68-543c45145ce9","internalTransactionId":"a53450cc-d24d-4af7-8291-34ec397527d4",
"upn":"<my user principal name>","tenantId":" Tenannt ID ","userObjectId":null}}

At C:\Tools\IntuneDocumentation-master\DocumentIntune.ps1:524 char:19
+ ... ite-Output (Invoke-RestMethod -Uri $url -Headers $header -Method GET  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Add-WordText : Object reference not set to an instance of an object.
At C:\Tools\IntuneDocumentation-master\DocumentIntune.ps1:1139 char:20
+ ... $Assignments | Add-WordText -FilePath $FullDocumentationPath -Size 12
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WordText], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,PSWord.AddWordText

**Comment by ThomasKur** [comment]
Ok, if you have to add AllowClobber then this means, that some of the commands are already available in another module with the same name. Therefore all important commands from the azuread module will have a prefix like Get-AZUREADADUser, which further explains the commands which are not working... because they are perhaps used from another module on you system. So please try it on another system...

**Comment by JanssenRemco** [comment]
Had the same issue here. After installing the AzureRM module without AllowClobber ("Install-Module AzureRM") the script ran perfect on my machine.

**Comment by ThomasKur** [comment]
CHeck out the new version which is using the Graph PowerShell Module. This one should work without an issue Invoke-IntuneDocumentation.ps1
