### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by Sittampalam** [ThomasKur/IntuneDocumentation#11]
Hello 
I have two factor authenticartion on my admin credentials so when I run the script it prompts me for my crentials but then does not ask for the second factor authentication and fails.

**Comment by ThomasKur** [comment]
Yes, it currently does not support MFA. I'm working on this functionality.

**Comment by Sittampalam** [comment]
Thank you for your response.

Nagu Sittampalam
Security Team Leader
IT Services,
Capita Southampton Limited (CSL),
Landline: 02380 833012 | Fax: 02380 832973
e-mail Nagu.Sittampalam@southampton.gov.uk<mailto:Nagu.Sittampalam@southampton.gov.uk> | e-mail Nagu.Sittampalam@capita.co.uk<mailto:Nagu.Sittampalam@capita.co.uk>
post Capita Southampton Limited (CSL), 1st Floor, One Guildhall Square, Above Bar, Southampton, SO14  7FP

**Comment by ThomasKur** [comment]
Check out the new version available Invoke-IntuneDocumentation.ps1
