### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by CoreyJSteele** [ThomasKur/IntuneDocumentation#15]
My Azure tenant uses MFA how would I change the code around lines 968 - 975 to leverage MFA?  I know it might be related to connect-MSOLService.  Im not sure how to gather the tokens etc.

Thanks

**Comment by ThomasKur** [comment]
Are you referring to the new version Invoke-IntuneDocumentation.ps1? This one should support MFA out of the box...

**Comment by ThomasKur** [comment]
Closed because of no feedback
