### ISSUE TITLE
Some details not showing in document

### ISSUE THREAD

**Issue by kailafoote** [ThomasKur/IntuneDocumentation#17]
Fantastic work here.  I'm compiling documentation for several different tenants am noticing some issues.  For example:

- one tenant I documented has Apple and Android apps deployed, only the Apple apps show in the application list in the word document
- another tenant has all Windows apps.  I saw the script get information about them but the Applications list in the Word document is empty.  

I'd like to work with you to troubleshoot.  Please contact me.

**Comment by ThomasKur** [comment]
Hello Timmmay

I would be happy to check what the issue is. I tried it in a few of my environments and always get all apps documented. So, do you see any errors during the generation?
If you connect to Intune by Powershell and execute then:

Get-IntuneMobileApp | Out-GridView 

Do you see then the missing applications?

Regards
Thomas

**Comment by kailafoote** [comment]
Thanks for the reply Thomas.

There are a couple of errors but none that relate to the applications list.

Errors when getting app protection policy information:
https://pastebin.com/q2icTTJe (the policy information is in the Word
document from what I can see)
Errors when getting device categories: https://pastebin.com/YdG3Hfi3 (the
device categories are missing from the Word document)

I ran the command and can see all of the applications.

I had added a couple of web links since I last tried the script for this
particular tenant.  The web links show, so do the iOS apps, but the managed
Google Play apps still are missing.  The @odata.type is
"#microsoft.graph.managedAndroidStoreApp".

Hope that helps!  Let me know what other testing I can do.

Cheers
Tim

**Comment by ThomasKur** [comment]
Ok, thank you. I worked today on the issue, I also saw that there are new Cmdlet's in the newest Intune PowerShell Module. As soon I have included them I will push the script updates.

**Comment by kailafoote** [comment]
Ok great, thanks for the update.  I'll keep my eye out for the release.
Happy to test for you as well.

**Comment by kailafoote** [comment]
Hey Thomas, just wondering if you have any update on this yet?

**Comment by ThomasKur** [comment]
Can you check again @timmmay ? I just published it as a PowerShell module on PSGallery.

```
Install-Module IntuneDocumentation
Invoke-IntuneDocumentation -FullDocumentationPath c:\temp\IntuneDoc.docx
```

**Comment by kailafoote** [comment]
Hi Thomas,

Nice work on the update!  The issues I reported here appear to have been resolved.  I came across a new one though so will log a new issue.  Cheers
