### ISSUE TITLE
App Config policies are mid-identified

### ISSUE THREAD

**Issue by poortom1004** [ThomasKur/IntuneDocumentation#20]
My App Config policies are getting identified as App Protection policies for some reason, in the word document that gets generated.  Also, there doesn't appear to be any meaningful configuration data that gets documented in those app protection policies.

**Comment by poortom1004** [comment]
typo in the title.  Meant to say mis-identified.

**Comment by ThomasKur** [comment]
Sorry for the delay. I'm checking it and will fix it.

**Comment by ThomasKur** [comment]
I checked it multiple times and never had this mismatch. If you have log files feel free to resubmit the issue.
