### ISSUE TITLE
DomainJoin (Preview) profiles are not captured by script

### ISSUE THREAD

**Issue by EdParraB** [ThomasKur/IntuneDocumentation#24]
Hi, ran the script and it worked like a charm but I had an issue with DomainJoin Configuration Profile in Intune. These are in Preview, but is there a way to update the script to capture those too? I have quite a few of those and it would be handy to have them included in the script ;)

**Comment by ThomasKur** [comment]
Hello @EdParraB thanks for the feedback. It's now part of the documentation. Please check it out.

**Comment by EdParraB** [comment]
awesome, thanks Thomas!
