### ISSUE TITLE
get-DeviceManagement_DeviceEnrollmentConfigurations_Assignment(s)

### ISSUE THREAD

**Issue by DJ-77** [ThomasKur/IntuneDocumentation#26]
I believe there is a typo in the invoke-intuneDocumentation.ps1    ###file.
@line 247 you call the command
Get-DeviceManagement_DeviceEnrollmentConfigurations_Assignment
where it should be
Get-DeviceManagement_DeviceEnrollmentConfigurations_Assignment**s**
#25

**Comment by ThomasKur** [comment]
Published in new version 2.0.13
