### ISSUE TITLE
IntuneDocumentation - module could not beloaded

### ISSUE THREAD

**Issue by JoPi2108** [ThomasKur/IntuneDocumentation#28]
Hi, we tried to install the Automatic Intune Documentation script with these commands:
Install-Module Microsoft.Graph.Intune
Install-Module PSWord
Install-Module IntuneDocumentation
Invoke-IntuneDocumentation -FullDocumentationPath c:\temp\IntuneDoc.docx
**=> Invoke-IntuneDocumentation : The 'Invoke-IntuneDocumentation' command was found in the module 'IntuneDocumentation' but the module could not be loaded.
CategoryInfo : ObjectNotFoud (IntuneDocumentation: string) [], CommandNotFoundException
FullyQualifiedErrorId: CouldNotAutoloadMatchingModule**

![Problem](https://user-images.githubusercontent.com/64961680/81288111-45c6b080-9064-11ea-94fe-df71201077aa.png)

I hope you can help?  Br / John

**Comment by kailafoote** [comment]
Hi John,

You need to import the modules before using them.  But I think only the
main one is required, so try this before running the
Invoke-IntuneDocumentation command:

Import-Module IntuneDocumentation

Cheers

**Comment by ThomasKur** [comment]
Has the import solved your issue?

**Comment by JoPi2108** [comment]
Hi Thomas, yes we did! It was something else; that by deafult we were not allowed to execute scripts ;) But we fixed that and the Intune doc is excellent. Thanks for your help!  Br / John
