### ISSUE TITLE
Include other app types

### ISSUE THREAD

**Issue by Belial2003** [ThomasKur/IntuneDocumentation#29]
When you change line 88 in Invoke-IntuneDocumentation.ps1 (#region Document Apps) from

> `Get-IntuneMobileApp | ForEach-Object {`

to

> `(Invoke-MSGraphRequest -HttpMethod GET -Url https://graph.microsoft.com/beta/deviceAppManagement/mobileApps).Value | ForEach-Object {`

you get all app types returned, including win32LobApp and officeSuiteApp.
Get-IntuneMobileApp uses https://graph.microsoft.com/**v1.0**/deviceAppManagement/mobileApps  which currently only returns part of the app types.

**Comment by ThomasKur** [comment]
Thanks @Belial2003 for the feedback. Just released a new version. :)
