### ISSUE TITLE
Add Endpoint Security Configurations to the script

### ISSUE THREAD

**Issue by mortengrundtvig** [ThomasKur/IntuneDocumentation#30]
Would be great to have the new Endpoint Security configurations included in the script. Maybe also the Security Baseline profiles

**Comment by ThomasKur** [comment]
Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
