### ISSUE TITLE
Can we somehow get all possible items that can be configured in Intune?

### ISSUE THREAD

**Issue by PJMarcum** [ThomasKur/IntuneDocumentation#31]
Would it be possible for you to add a switch that would allow us to dump out all of the items in Intune that can be configured? Sadly customers want to see what they can do before they decide what they want to do. I used to have this as an Excel that I manually created but it was just too much to keep it up to date.

**Comment by ThomasKur** [comment]
You mean like creating a word file and create the tables like now, but without values and in addition also create the section and tables for the profiles where non is available? 

I could dump all the profiles as json into the module. But this requires updating the module when graph api changes. Because I don't like connecting for example to github and download it from there.

**Comment by PJMarcum** [comment]
Not exactly. Just a switch to dump everything into a doc without values. Not worried about configured values in this doc, that's a separate doc. The scenario is..... Before work begins on a project, sit down with the customer and design what will be configured. We would use this sheet to mark down what they agree will be configured and have them sign off on it. Then we build the environment and but out the configured values into a new doc to show that what was agreed upon is what was done.

**Comment by LSTEK** [comment]
It might be worth taking what Anoop has done and updating it slightly rather than this: [anoopcnair](https://www.anoopcnair.com/intune-configuration-spreadsheet/). 
Hope that helps.

**Comment by ThomasKur** [comment]
thanks for this input. This is great, I will check if it somehow would be possible to perhaps generate exactly these or similar files in the future. I work already on it.

**Comment by PJMarcum** [comment]
The Excel that's posted above looks curiously like the one that I made public several years ago. It was created manually and it was a giant headache to keep it updated. What I do is create a bunch of empty policies and use your script to create a doc and use that for a template to do a recommendations doc.

**Comment by johofer** [comment]
This is a great idea and would also make it possible to identify changes to policies (added/removed attributes) by just exporting them programmatically eg. on 01.01.2021 and on 01.02.2021 then comparing them. 
By identifiying those changes you can advise your customers to change policies if it makes sense for them. The "what's new" and "in development" pages sometimes don't tell the whole story ;)

**Comment by ThomasKur** [comment]
Happy to announce the https://github.com/ThomasKur/M365Documentation

Here you can compare changes: https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/

There is also the option to output to CSV files.

Additionally, the Optimize-M365Doc command supports now the -ExcludeValues parameter which will create an empty documentation.

**Comment by LSTEK** [comment]
Fantastic & great work!
