### ISSUE TITLE
Non interactive generation

### ISSUE THREAD

**Issue by Kirikou974** [ThomasKur/IntuneDocumentation#33]
Hello,

I'm trying to run this script automatically without user interaction.
It looks like it's not possible because of the "Connect-MSGraph" call.
My guess is that Connect-MSGraph tries to prompt for the user credentials which doesn't work when starting this script in an automated and unattended way.
Connect-MSGraph does provide some switches that could be used to remove the need of user interaction like : 
- ClientSecret : providing an app client secret looks like the best way IMHO
- Credential : providing a credential object that could be built automatically when script executes

What's your take on this one ?

**Comment by redkaffe** [comment]
nice catch, that would allow scheduling the script to generate the documentation at fixed intervals or in a pipeline when a change is known to happen

**Comment by ThomasKur** [comment]
Just released new version to PS Gallery with support for silent execution.
https://www.powershellgallery.com/packages/IntuneDocumentation/2.0.16

Documentation for usage available here:
https://github.com/ThomasKur/IntuneDocumentation#use-script-silently 

Happy to get feedback from you!
