### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Xtraim** [ThomasKur/IntuneDocumentation#34]
hi,
first time i use this wonderfull tool.
I get this erros :

Get-DeviceAppManagement_AndroidManagedAppProtections_Assignments : 400 Bad Request
{
  "error": {
    "code": "No method match route template",
    "message": "No OData route exists that match template ~/singleton/navigation/key/cast/navigation with http verb
GET for request /MAMAdmin_2007/MAMAdminFEService/deviceAppManagement/androidManagedAppProtections('T_efc4d995-xxxx-yyyy-zzzz-fcc96b9d1b0d')/$/microsoft.management.services.api.androidManagedAppProtection/assignments.",
    "innerError": {
      "date": "2020-07-24T07:22:49",
      "request-id": "a756e412-a056-4227-acda-08aa6800478d"
    }
  }
}
Au caractère C:\Program
Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.16\Functions\Invoke-IntuneDocumentation.ps1:159 : 25
+ ...     $MAMA = Get-DeviceAppManagement_AndroidManagedAppProtections_Assi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-DeviceAppMa...ons_Assignments],
   HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlet
   s.Get_DeviceAppManagement_AndroidManagedAppProtections_Assignments

**Comment by ThomasKur** [comment]
Thanks for the feedback. i have already found a solution. I will publish a new version in the next days with the fix.

**Comment by ThomasKur** [comment]
Part of the 2.0.17 , please try it out.

**Comment by Xtraim** [comment]
that works now ! thanks :)
