### ISSUE TITLE
typo and suggestion to report on assignment intent in Invoke-PrintAssignmentDetail function

### ISSUE THREAD

**Issue by GregO-MM** [ThomasKur/IntuneDocumentation#36]
Hi,

In Invoke-PrintAssignmentDetail  at string 21 it is 

foreach($group in $DCPA)

but should be 

foreach($group in $Assignments)

Best regards

**Comment by GregO-MM** [comment]
Also in function Invoke-PrintAssignmentDetail would suggest to document assignment type:

`
foreach($group in $Assignments){
	if(($null -ne $group.target.groupId) -and ($null -ne $group.target.'@odata.type')){
		if ($group.target.'@odata.type' -notlike "*exclusion*") {$tempAssignmentType = "Include"} else {$tempAssignmentType = "EXCLUDE"}
		$AssignmentsList += "$((Get-AADGroup -groupid $group.target.groupId).displayName + " - $tempAssignmentType")"
                }
`

**Comment by ThomasKur** [comment]
Thanks for your feedback. The first one will be in the next release. 

To add the type of assignment I need to investigate a little bit deeper because not all configurations result with the same assignment objects. But definitely I will add this functionality... but need a few days

**Comment by ThomasKur** [comment]
Assignment type (Include/Exclude) is now documented. Will be in the next release.
