### ISSUE TITLE
Unable to download/get the Intune Documentation

### ISSUE THREAD

**Issue by ananthsubklt** [ThomasKur/IntuneDocumentation#4]
Hi,

I am unable to get the documentation..looks it looks for Global Azure Admin credentials? Is it so? Not sure why? Can you advice?

Thanks much,
Anantha

**Comment by ThomasKur** [comment]
Hello Anantha,

Yes, the first time, this is required to create the SaaS App to allow Access to the Graph API over PowerShell. 

I suggest to let a Global Admin execute the Script the first time. Othwise you have to send them a manual about how to create the Application described here:
https://docs.microsoft.com/en-us/intune/intune-graph-apis

Client id has to be: d1ddf0e4-d672-4dae-b554-9d5bdfd93547

Regards
Thomas
