### ISSUE TITLE
A bit large

### ISSUE THREAD

**Issue by kevsully** [ThomasKur/IntuneDocumentation#40]
This is a great idea. I think Word may not be the right tool For example, if I want to document all APPs across a tenant seeing those in a list, non relative to each other, is still very tricky to parse. If the output was into say excel or even CSV you could have a excel page in a workbook for APPs and each row is a single APP each column is an attribute and you could quickly at a glance see which settings were common across polities. Then another page for Device Configuration, Device Compliance etc. etc. 

My small test lab generated a 120 page document that was very interesting but I'm not sure how it would be in a production environment. Just a thought.

**Comment by ThomasKur** [comment]
Thanks for the feedback... currently there is a work in progress with the goal to allow the generation only for parts of the infrastructure and additionally output to various targets (html, csv, docx, ...)
