### ISSUE TITLE
How to create extra Translation fields

### ISSUE THREAD

**Issue by ThijsLecomte** [ThomasKur/IntuneDocumentation#41]
In the output of my script, I received the following output:
```
WARNING: 2020-10-23 10:56:59+02 WARN You used the option to translate API properties. Some of the configurations of
your tenant could not be translated because translations are missing.
WARNING: 2020-10-23 10:56:59+02 WARN  - C:\Program
Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.15\Data\LabelTranslation\#microsoft.graph.androidDeviceOwnerGen
eralDeviceConfiguration.json
WARNING: 2020-10-23 10:56:59+02 WARN  - C:\Program
Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.15\Data\LabelTranslation\#microsoft.graph.androidCustomConfigur
ation.json
WARNING: 2020-10-23 10:56:59+02 WARN  - C:\Program
Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.15\Data\LabelTranslation\#microsoft.graph.iosWiFiConfiguration.
json
WARNING: 2020-10-23 10:56:59+02 WARN  - C:\Program
Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.15\Data\LabelTranslation\#microsoft.graph.androidGeneralDeviceC
onfiguration.json
WARNING: 2020-10-23 10:56:59+02 WARN You can support the project by translating and submitting the files as issue on
the project page. Then it will be included for the future.
WARNING: 2020-10-23 10:56:59+02 WARN Follow the guide here
https://github.com/ThomasKur/IntuneDocumentation/blob/master/AddTranslation.md

```
I would love to create Translation Files for the Security Baseline (the new Endpoint Security nodes), but I am not sure how to create these files? How can I find the correct DataType and Metadata.
Is this something that can be generated through a script? I am happy to contribute to this

**Comment by ThomasKur** [comment]
Hello @ThijsLecomte 

That woud be great! There is a short manual available here: https://github.com/ThomasKur/IntuneDocumentation/blob/master/AddTranslation.md

If you commit to this repository, just add them to the following repo directory PSModule\IntuneDocumentation\Data\LabelTranslation\ or attach them to this issue

**Comment by ThijsLecomte** [comment]
Hi @ThomasKur 

I had seen this, but the docs state:
Open one of the displayed json files which are displayed after you generated the documentations.

And I am not seeing any json files for the Security Baselines?
![image](https://user-images.githubusercontent.com/42153270/97020854-5d322100-1552-11eb-8626-372196430160.png)

**Comment by ThomasKur** [comment]
ok, I will check this!
