### ISSUE TITLE
Own template possible?

### ISSUE THREAD

**Issue by Phoenix-DH** [ThomasKur/IntuneDocumentation#42]
Hey,

I am triing to use an own template.
I read that there must just be a "Template.docx" in the same location where I got my script located which runs "Invoke-IntuneDocumentation".
But this is not working.

I created a script called "IntuneDocumentation.ps1" to have some stuff arround and placed the "Template.docx" in the same location.

Thanks.

**Comment by ThomasKur** [comment]
Hello @Phoenix-DH ,

Ok, here is the manual not 100% correct. You need to:

- replace the Template.docx in the Modules directory or 
- you can just specify an existing word file in the FullDocumentationPath parameter. Then the content will just attach to this document.


Does this help?

**Comment by Phoenix-DH** [comment]
Thanks!
I already got it.
