### ISSUE TITLE
API names to portal names

### ISSUE THREAD

**Issue by Perrinw** [ThomasKur/IntuneDocumentation#43]
Hello, I’m trying to contribute to the API names to portal names for this script. I’m following the directions on https://github.com/ThomasKur/IntuneDocumentation/blob/master/AddTranslation.md but I do not get anything for this step “Open one of the displayed json files which are displayed after you generated the documentations.”

running this command- Invoke-IntuneDocumentation -FullDocumentationPath c:\temp\IntuneDoc.docx -UseTranslationbeta

thank you

**Comment by ThomasKur** [comment]
Hello, the script generates the JSON files and displays them as soon you have profiles in your environment. Do you don't get an output? Can you send me a screenshot of the windows?
