### ISSUE TITLE
Limit of 1000 results - pagination missing

### ISSUE THREAD

**Issue by Phoenix-DH** [ThomasKur/IntuneDocumentation#53]
We have in our environment in some regions more than 1000 elements.
For example in applications.

We figured out that there are only 1000 apps visible in the document.

From other projects I know that the normal limit for graph calls is 1000.
Maybe it is possible to add an pagination to your script too?

Thank you.

**Comment by ThomasKur** [comment]
Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
