### ISSUE TITLE
Errors when running the script

### ISSUE THREAD

**Issue by nirender** [ThomasKur/IntuneDocumentation#54]
When I run the script for conditional access I get these two errors. It does not prevent the script from running and producing the documents

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Get-AzureADUser.ps1:27 char:9
+         $errorResponse = $ex.Response.GetResponseStream()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Get-AzureADUser.ps1:27 char:9
+         $errorResponse = $ex.Response.GetResponseStream()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

 Any help appreciated

Nirender

**Comment by ThomasKur** [comment]
This is now solved in the [Automatic Microsoft 365 Documentation](https://github.com/ThomasKur/M365Documentation).
