### ISSUE TITLE
Error on line 954 IntunDocumentation script

### ISSUE THREAD

**Issue by RuudGijsbers** [ThomasKur/IntuneDocumentation#6]
https://github.com/ThomasKur/IntuneDocumentation/blob/41979a9c2226e268c5b96f01553c0c5178a997b7/DocumentIntune.ps1#L954

There's a space to much on this line. Therefor the script didn't work when I tried it.

**Comment by ThomasKur** [comment]
Just removed the space. Thanks for the feedback!
