### ISSUE TITLE
Document Application settings

### ISSUE THREAD

**Issue by SobreroD** [ThomasKur/IntuneDocumentation#63]
It would be outstanding to have each of the applications broken down to Windows / Mac / Mobile and provide details of each application via a -MaxDetails switch. showing install/uninstall command lines and other information. this information is stored in JSON file so I'm not sure if you can extract that information and import it into readable format.

**Comment by ThomasKur** [comment]
Thank you for the feedback. I'm working on it.

**Comment by ThomasKur** [comment]
This is now possible in the [Automatic Microsoft 365 Documentation](https://github.com/ThomasKur/M365Documentation).
