### ISSUE TITLE
Cannot enable logging to a file

### ISSUE THREAD

**Issue by rk-h** [ThomasKur/IntuneDocumentation#65]
As I understood it - to turn on logging to a log file - I need to modify the file ..\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Write-Log.ps1. I must change the value $OutputMode = "Console" to $OutputMode = "Console-LogFile". Is this correct?

If I do that, afterwards the module does not work anymore. I suspect that this has to do with the signature of the scripts. If I downloaded the script via PS Gallery, how do I turn on logging to a file?

**Comment by ThomasKur** [comment]
This was not supported. 

Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
