### ISSUE TITLE
Heading in document does not work when changing the template

### ISSUE THREAD

**Issue by gijsprins93** [ThomasKur/IntuneDocumentation#66]
Hi,

I have changed the template to have our own logo and the date formatting to use dashes instead of dots. Only that is being edited, but then the heading in Word just doesn't work anymore. It's normal text suddenly. How can that be?

**Comment by ThomasKur** [comment]
Hello, 
I recommend to use the new module which is much more flexible and maintained: https://github.com/ThomasKur/M365Documentation
