### ISSUE TITLE
UserExcludeGroups not correctly documented

### ISSUE THREAD

**Issue by slueders-bag** [ThomasKur/IntuneDocumentation#69]
The value UserExcludeGroups does not have the correct values. It adds all exlusiongroups for each policy. So for example if you have 3 policies and each policy has a exclusion set, policy 3 has the exclusions of policy 1 and 2 also documented.

**Comment by ThomasKur** [comment]
Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
