### ISSUE TITLE
Failed to retrieve access token from Azure

### ISSUE THREAD

**Issue by micheltenhove** [ThomasKur/IntuneDocumentation#7]
I'm receiving the following error when I run the script, perhaps I'm missing something here? :-)

![error](https://user-images.githubusercontent.com/40995270/42444879-986a38a4-8371-11e8-94f5-5b513935f8eb.PNG)

**Comment by ThomasKur** [comment]
Sorry for the delayed answer: Can you try to register Intune PowerShell Access in your Azure AD. Perhaps this is not already done in your tenant:

https://login.microsoftonline.com/$Tenant/oauth2/authorize?client_id=d1ddf0e4-d672-4dae-b554-9d5bdfd93547&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_mode=query&resource=https%3A%2F%2Fgraph.microsoft.com%2F&state=12345&prompt=admin_consent

Replace $Tenant with your UPN of the username and then Open the url in a browser...

**Comment by lwhitworth** [comment]
I'm seeing the same issue.  If I disable MFA on my account it gets a lot further, but eventually hit:
```
The remote server returned an error: (400) Bad Request. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: <snip>: Due to a configuration change made by your administrator, or because you moved to a new
location, you must enroll in multi-factor authentication to access
```
Turning back on MFA I go back to the "Failed to retrieve access token from Azure" error.

**Comment by PeterSelchDahl** [comment]
Hi,

Just replace the "$Tenant" with your tenant ID an run the script again.
![tenant](https://user-images.githubusercontent.com/7662528/43523889-0a855f84-959e-11e8-9c97-f2e8b48d5a7d.png)

If it still does not work as expected you should double check that you have provided consent as mentioned by Thomas
![consent](https://user-images.githubusercontent.com/7662528/43524001-60b198fa-959e-11e8-8af8-075190b6d531.png)

Provide consent by using the steps mentioned by Thomas.

For reference.
![2018_08_01_14_54_26_windows_powershell_ise](https://user-images.githubusercontent.com/7662528/43523688-7ac68800-959d-11e8-98c3-c7c422e4ab5f.png)
![2018_08_01_14_55_21_windows_powershell_ise2](https://user-images.githubusercontent.com/7662528/43523705-89d904d0-959d-11e8-926a-5c5c5c8b2c30.png)

/Peter Selch Dahl
Azure MVP

**Comment by ThomasKur** [comment]
Thanks Peter for your answer.

**Comment by lrh-albert** [comment]
I encountered similar issue `Error: Failure when retrieving tokens` while using azure data studio in macOS 10.15.4（19E266）,   and the url was like `https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&response_mode=query&client_id=a69788c6-1d43-44ed-9ca3-b83e194da255&redirect_uri=https%3A%2F%2Fvscode-redirect.azurewebsites.net%2F&state=53697%2CgbLs14mTaDgAVCmijcHLvA%253D%253D&prompt=select_account&code_challenge_method=S256&code_challenge=oXKihXyp7aZbsGHKh4LYW2_J-BxcNVsJ6wAXW_ihJCI&resource=https%3A%2F%2Fmanagement.core.windows.net%2F`

I've tried changing $Tenant,  which is "common" in this case, into my tenant ID, however, it didn't work for me.
Seek for more info about this issue and thanks a lot!

**Comment by ThomasKur** [comment]
As I see you are using macOS: This is currently not supported by the underlying Intune PowerShell Module. Can you try it on a Windows Device?

**Comment by lrh-albert** [comment]
As you suggested I've tried it on Windows Device before macOS and it worked well
Thanks for your help so I will not waste time on it on macOS lol
