### ISSUE TITLE
Get-Groups and Add-WordTable throwing all kinds of errors

### ISSUE THREAD

**Issue by eddie-jimenez** [ThomasKur/IntuneDocumentation#70]
`Get-Groups : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '436e7548-cf13-48cd-a558-35ff17ccf057' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:33:58","request-id":"bf4cfcdb-a6c6-4e60-a21f-64ce0d98c9a5","client-request-id":"bf4cfcdb-a6c6-4e60-a21f-64ce0d98c9a5"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:25 char:21
+         $GroupObj = Get-Groups -groupid $Assignment.target.groupId
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups
 
Get-Groups_Members : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '436e7548-cf13-48cd-a558-35ff17ccf057' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:33:58","request-id":"a897602b-fd77-449d-a154-ee9fca5a507b","client-request-id":"a897602b-fd77-449d-a154-ee9fca5a507b"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:36 char:20
+ ...     $Members = Get-Groups_Members -groupId $Assignment.target.groupId
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups_Members], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups_Members
 
Add-WordTable : Object reference not set to an instance of an object.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail.ps1:29 char:33
+ ... endedInfo | Add-WordTable -FilePath $FullDocumentationPath -AutoFitSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (System.NullRefe...ProcessRecord():NullReferenceException) [Add-WordTable], NullReferenceException
    + FullyQualifiedErrorId : -2147467261,PSWord.AddWordTable
 
Get-Groups : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource 'fd764199-dfac-4ea3-826b-00a04d8e78d6' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:34:57","request-id":"8eb5d13e-63eb-494d-8434-280c2afada51","client-request-id":"8eb5d13e-63eb-494d-8434-280c2afada51"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:25 char:21
+         $GroupObj = Get-Groups -groupid $Assignment.target.groupId
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups
 
Get-Groups_Members : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource 'fd764199-dfac-4ea3-826b-00a04d8e78d6' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:34:58","request-id":"b25023a6-07c4-46b6-ac65-4b992ec241be","client-request-id":"b25023a6-07c4-46b6-ac65-4b992ec241be"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:36 char:20
+ ...     $Members = Get-Groups_Members -groupId $Assignment.target.groupId
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups_Members], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups_Members
 
Add-WordTable : Object reference not set to an instance of an object.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail.ps1:29 char:33
+ ... endedInfo | Add-WordTable -FilePath $FullDocumentationPath -AutoFitSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (System.NullRefe...ProcessRecord():NullReferenceException) [Add-WordTable], NullReferenceException
    + FullyQualifiedErrorId : -2147467261,PSWord.AddWordTable
 
Get-Groups : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '5763aab5-92e2-4fa3-ba55-3adbcf22259c' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:35:10","request-id":"e0640366-650d-49a3-ab56-8e7b365d9d1b","client-request-id":"e0640366-650d-49a3-ab56-8e7b365d9d1b"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:25 char:21
+         $GroupObj = Get-Groups -groupid $Assignment.target.groupId
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups
 
Get-Groups_Members : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '5763aab5-92e2-4fa3-ba55-3adbcf22259c' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:35:10","request-id":"c8b6b8ba-eaf9-4dbd-a7a9-c3a3969a10c4","client-request-id":"c8b6b8ba-eaf9-4dbd-a7a9-c3a3969a10c4"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:36 char:20
+ ...     $Members = Get-Groups_Members -groupId $Assignment.target.groupId
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups_Members], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups_Members
 
Get-Groups : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '3089a5d6-4a6f-4e92-aa27-beceefd4d0a1' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:35:10","request-id":"179eda17-4abf-4dae-9379-31bb184ba58a","client-request-id":"179eda17-4abf-4dae-9379-31bb184ba58a"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:25 char:21
+         $GroupObj = Get-Groups -groupid $Assignment.target.groupId
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups
 
Get-Groups_Members : 404 Not Found
{"error":{"code":"Request_ResourceNotFound","message":"Resource '3089a5d6-4a6f-4e92-aa27-beceefd4d0a1' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-09-28T22:35:11","request-id":"64214875-4db4-49d4-998c-ee13814a154f","client-request-id":"64214875-4db4-49d4-998c-ee13814a154f"}}}
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail_Assignment.ps1:36 char:20
+ ...     $Members = Get-Groups_Members -groupId $Assignment.target.groupId
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-Groups_Members], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_Groups_Members
 
Add-WordTable : Object reference not set to an instance of an object.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail.ps1:29 char:33
+ ... endedInfo | Add-WordTable -FilePath $FullDocumentationPath -AutoFitSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (System.NullRefe...ProcessRecord():NullReferenceException) [Add-WordTable], NullReferenceException
    + FullyQualifiedErrorId : -2147467261,PSWord.AddWordTable
 
Add-WordTable : Object reference not set to an instance of an object.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\2.0.19\Internal\Invoke-PrintAssignmentDetail.ps1:29 char:33
+ ... endedInfo | Add-WordTable -FilePath $FullDocumentationPath -AutoFitSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (System.NullRefe...ProcessRecord():NullReferenceException) [Add-WordTable], NullReferenceException
    + FullyQualifiedErrorId : -2147467261,PSWord.AddWordTable
 `

**Comment by ThomasKur** [comment]
Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
