### ISSUE TITLE
Configuration Profile Type Settings Catalog not being exported

### ISSUE THREAD

**Issue by fwotherspoon** [ThomasKur/IntuneDocumentation#71]
When running the command the resulting Word doc doesn't have any Configuration Profiles where the profile type is Settings Catalog.

I am in the process of moving to this type of profile, so would be great to be able to capture these settings without having to create it manually.

**Comment by ThomasKur** [comment]
Please use the new module with a lot more functions M365Documentation.

https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/
