### ISSUE TITLE
Headers in Device Platform restrictions

### ISSUE THREAD

**Issue by TassieTrooper** [ThomasKur/IntuneDocumentation#72]
Hi,

When adding an Intune enrolment device platform restriction, it is not clear that the device manufacturer is 'allowed' or is to be 'blocked', considering that all the options are set to 'Allow' and the header reads 'Device Manufacturer' singular. It should have the header, field or a tooltip state 'Blocked Manufacturers' as it displays this the overview page for the restrictions.

Would be nice to have this other way around in my assessment, or a toggle to allow/block for the manufacturer entered. 

As I novice I was pulling my hair out thinking I was only 'Allowing' a specific type of device manufacturer to enroll.

![2022-11-04 15_24_07-Allow Yealink MDM Enrolment - Microsoft Endpoint Manager admin center and 4 more](https://user-images.githubusercontent.com/3481012/199900257-1af13785-79de-4ed9-a21e-d013e17a9702.png)
![2022-11-04 15_52_28-Edit restriction - Microsoft Endpoint Manager admin center - Work - Microsoft​ E](https://user-images.githubusercontent.com/3481012/199900265-cfac0713-1ffd-4d74-8cd2-d10cb0ed1d7b.png)

**Comment by ThomasKur** [comment]
Hello TassieTrooper

Please use the evolved M365Documentation script which provides more options:
https://www.wpninjas.ch/2021/05/automatic-intune-documentation-evolves-to-automatic-microsoft365-documentation/

**Comment by TassieTrooper** [comment]
OK Im not following :/ Shame it just can't say 'Blocked...'
