### ISSUE TITLE
Failed to retrieve access token from Azure

### ISSUE THREAD

**Issue by KennethBess** [ThomasKur/IntuneDocumentation#8]
Hi,

When running the script, you'll get a error "Failed to retrieve access token from Azure"

**Comment by jflieben** [comment]
Could you provide more information? I just ran the script with no issues here. Do you have the prerequisite modules and permissions? Is this the only error? What do you get in verbose mode?

**Comment by ThomasKur** [comment]
Could it be, that it is the same like here https://github.com/ThomasKur/IntuneDocumentation/issues/7

**Comment by KennethBess** [comment]
@ThomasKur - It was exactly this. Thanks, it now works.

**Comment by ThomasKur** [comment]
Perfect, I wish happy documenting
