### ISSUE TITLE
Support for Azure MFA

### ISSUE THREAD

**Issue by Skorfulose** [ThomasKur/IntuneDocumentation#9]
We have required MFA via AAD Conditional Access for all our admins. Hence the auth tokens cannot be retrieved. Is there a workaround?

Even better would be to run this script with non-user credentials, e.g. thru Azure Automation. Any thoughts on that?

Explanation:
Our use case is that we have three independent tenants (Development, Integration and Production) and want to regularly create reports for all three to manually check for config deviations.
Eventually we dream of continuous integration/deployment. But that would definitely require an official Graph API endpoint to read/write Conditional Access policies.

**Comment by ThomasKur** [comment]
No at the moment there is no work around. But I will add it to the wish list.
